### PR TITLE
New age_range attribute in Age

### PR DESCRIPTION
**Pull request by mbaudis**
The representation of ages of unknown "point value", but lying within a certain range, is a requirement in the representation of many biomedical data collections. Typical instances here would be clinical studies with known inclusion ages ("adults 18-65ys") or research projects targeting age delimited populations, without individual age data.
It has not escaped our notice[<sup>TM</sup>](http://www.lablit.com/article/11) that the representation of an `age_range` in conformance with the [FHIR Range model](http://build.fhir.org/datatypes.html#Range) (sorted array of 1 or 2 values; thanks @julesjacobsen) would obviate the need of an atomic `age` attribute; but this is a topic for discussion.

Please note that the fix of the "age_class" example is separately covered in #6 .

For the code review, please focus on the [YAML source file](https://github.com/ga4gh-schemablocks/blocks/compare/Age-age-to-range?expand=1#diff-8af9914a343a0bb2fe756c7c70d45db0).

### CODE REVIEW

**Comment by Relequestual** [comment]
It looks like a LOT of the diff we're seeing here is a re-ordering of keys in the resulting JSON. This makes it super hard for anyone to really see what has or has not changed.

Can I suggest that while we continue to use this non standard tooling, to canonically encode the JSON to make diffs clearer?
You would need to create a new PR or commit having re-encoded canonically, and rebase the PR onto it.

https://metacpan.org/pod/JSON::XS#$json-=-$json-%3Ecanonical-([$enable])

**Comment by mbaudis** [comment]
@relequestal You’re right that this is messy & needs improvement.  However, writing in JSON doesn‘t help since the YAML is the source; and same would happen if swapping the processing direction. 
I propose to have this right now by
• do more on the discussion on the „issue“ level and only PR when more mature
• only edit the source & don’t do doc builds on branches (apologies, shouldn’t have done this in the first place)
• update the script to preserve object ordering

**Comment by Relequestual** [comment]
I was talking about changing the script to canonically encode the JSON, which should make the conversion from source YAML to JSON consistnet.

No one wants to write JSON by hand! =]

**Comment by mbaudis** [comment]
@Relequestual I've cleaned up... Thanks for the `canonical` suggestion; wasn't aware of it and about to write a method myself :-/  Still have to test it.

**Comment by Relequestual** [comment]
@mbaudis Welcome!

**Comment by mbaudis** [comment]
@Relequestual finally cleaned the ordering, for future use ... Still messy PR due to the flip-flopping between updates... ?

@julesjacobsen Can you check how the age_range now looks? There is no separate "age as point value" object; such ages are simply declared as ISO8601 strings, in 3 different positions (`age` as well as `age_range.star`, `age_range.end`:
https://github.com/ga4gh-schemablocks/blocks/pull/7/files#diff-8af9914a343a0bb2fe756c7c70d45db0R30

In principle one could have a "numeric_age" object for those, which could use other concepts, too (e.g. one_of ISO or age_with_unit). Wouldn't be recursive. But such things should be left IMO to implementations, where the local use case is translated into ISO.

**Comment by mbaudis** [comment]
Merging for cleanup; possible discussions in later alignment.

**Pull request merged**
